### ISSUE TITLE
"Docs" tab issues

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#70]
Hi,

I used to be able to start typing the namespace in the "Docs" tab and things worked correctly, for instance if I started typing "mojo.graphics." it instantly showed me the correct page in the help viewer, before I was even done with typing. Now it doesn't do anything, even if I finish typing the namespace and hit enter in the previous example.

:-(

Another minor quibble: The modules aren't listed alphabetically:
<img width="635" alt="screen shot 2017-11-18 at 8 51 23 pm" src="https://user-images.githubusercontent.com/6250116/32987484-4a8ba39c-cca2-11e7-98d1-3a5252e5b36a.png">

Thanks!

**Comment by engor** [comment]
1. I pushed fix into dev - now it searching by namespace. Try it out.
2. "The modules aren't listed alphabetically" - I can't see that, my list is sorted.

**Comment by DoctorWhoof** [comment]
Yes, searching with namespace seem to work now. Thanks.
Sorting still doesn't work here, may be a MacOS thing?

**Comment by engor** [comment]
@DoctorWhoof try to uncommets `line 196 in /view/HelpTreeView.monkey2` file.

**Comment by DoctorWhoof** [comment]
Will try when I get home later tonight, thanks!

**Comment by DoctorWhoof** [comment]
Sorry, forgot about this.
Yay! That works, modules are listed in correct order. Can you push that change into dev? Thanks!
